#!/bin/bash

# Usage git-clone-add-user [repo] [user] [email]

if [ "$#" -ne 3 ]; then
  echo "Illegal number of parameters. Usage:"
  echo "git-clone-add-user [repo] [user] [email]"
else
  git clone $1 && cd $(basename $1 .git)
  git config --local --add user.name $2
  git config --local --add user.email $3
fi
